### ISSUE TITLE
Running locally

### ISSUE THREAD

**Issue by jamesevickery** [hmrc/trust-registration-api#242]
Trying to run the Trust Registration API locally using [service manager](https://github.com/hmrc/service-manager) requires 'Nexus' credentials. I've seen a [similar issue](https://github.com/hmrc/self-assessment-api/issues/446) raised on the [self-assessment-api repo](https://github.com/hmrc/service-manager), suggesting that is an internal tool.

The reply was:

> Unfortunately it will not be possible for you to run this project locally as it depends on some internal libraries that are not public

Is this the case for the Trust Registration API, or can this be run locally for testing _outside of HMRC_?

**Comment by versatil56** [comment]
Hello @jamesevickery 

You are right, this is not possible at the minute because the project depends on internal libraries that are not public.

Many Thanks

Juan.

**Comment by jamesevickery** [comment]
Okay, thank you @versatil56.

Do you know when documentation for this API is likely to be available?
